[workspace]
members = ["crates/*", "examples/*"]
resolver = "2"

[workspace.package]
version = "0.10.0"
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2024"
repository = "https://github.com/mbrea-c/bevy_animation_graph"

[workspace.dependencies]
bevy_animation_graph_proc_macros = { version = "0.10.0", path = "./crates/bevy_animation_graph_proc_macros" }
bevy_animation_graph = { version = "0.10.0", path = "./crates/bevy_animation_graph" }
bevy_animation_graph_core = { version = "0.10.0", path = "./crates/bevy_animation_graph_core" }
bevy_animation_graph_builtin_nodes = { version = "0.10.0", path = "./crates/bevy_animation_graph_builtin_nodes" }

bevy = { git = "https://github.com/bevyengine/bevy", branch = "main" }
avian3d = { git = "https://github.com/slyedoc/avian", branch = "bevy-main" }

egui_dock = "0.18"
egui-notify = { version = "0.21" }
egui = { version = "0.33" }
egui_extras = { version = "0.33", features = ["all_loaders"] }
bevy_egui = { git = "https://github.com/slyedoc/bevy_egui", branch = "bevy-main" }
bevy-inspector-egui = { git = "https://github.com/slyedoc/bevy-inspector-egui", branch = "bevy-main" }

ron = "0.10.1"
serde = { version = "1.0" }

[patch."https://github.com/bevyengine/bevy"]
bevy = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }
bevy_a11y = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }
bevy_animation = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }
bevy_anti_alias = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }
bevy_app = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }
bevy_asset = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }
bevy_audio = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }
bevy_camera = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }
bevy_color = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }
bevy_core_pipeline = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }
bevy_derive = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }
bevy_diagnostic = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }
bevy_ecs = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }
bevy_feathers = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }
bevy_gilrs = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }
bevy_gizmos = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }
bevy_gizmos_render = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }
bevy_gltf = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }
bevy_image = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }
bevy_input = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }
bevy_input_focus = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }
bevy_internal = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }
bevy_light = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }
bevy_log = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }
bevy_material = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }
bevy_math = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }
bevy_mesh = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }
bevy_pbr = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }
bevy_picking = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }
bevy_platform = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }
bevy_post_process = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }
bevy_ptr = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }
bevy_reflect = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }
bevy_remote = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }
bevy_render = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }
bevy_scene = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }
bevy_shader = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }
bevy_sprite = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }
bevy_sprite_render = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }
bevy_state = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }
bevy_tasks = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }
bevy_text = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }
bevy_time = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }
bevy_transform = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }
bevy_ui = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }
bevy_ui_render = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }
bevy_ui_widgets = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }
bevy_utils = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }
bevy_window = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }
bevy_winit = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }
bevy_world_serialization = { git = "https://github.com/slyedoc/bevy", branch = "bsn2" }

[patch.crates-io]
parry3d = { git = "https://github.com/slyedoc/parry", branch = "bevy-main" }
parry3d-f64 = { git = "https://github.com/slyedoc/parry", branch = "bevy-main" }
glamx = { git = "https://github.com/slyedoc/glamx", branch = "bevy-main" }
